// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC83S8AY5DVNJv6ieEU165Eh8DgpVjsPQE',
    appId: '1:32021205715:web:3c60c387721aeb08093a26',
    messagingSenderId: '32021205715',
    projectId: 'olivosverdes-34cf7',
    authDomain: 'olivosverdes-34cf7.firebaseapp.com',
    storageBucket: 'olivosverdes-34cf7.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCzixOlWPzYhxU0BSd2brVP0fZuZhyo84A',
    appId: '1:32021205715:android:e0ca1162cc71a6e1093a26',
    messagingSenderId: '32021205715',
    projectId: 'olivosverdes-34cf7',
    storageBucket: 'olivosverdes-34cf7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBz_Usq3bbFzDsXNLVcxLt6GNVbHjEmJkY',
    appId: '1:32021205715:ios:d86b979639858589093a26',
    messagingSenderId: '32021205715',
    projectId: 'olivosverdes-34cf7',
    storageBucket: 'olivosverdes-34cf7.firebasestorage.app',
    iosBundleId: 'com.example.olivosVerdes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBz_Usq3bbFzDsXNLVcxLt6GNVbHjEmJkY',
    appId: '1:32021205715:ios:d86b979639858589093a26',
    messagingSenderId: '32021205715',
    projectId: 'olivosverdes-34cf7',
    storageBucket: 'olivosverdes-34cf7.firebasestorage.app',
    iosBundleId: 'com.example.olivosVerdes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC83S8AY5DVNJv6ieEU165Eh8DgpVjsPQE',
    appId: '1:32021205715:web:8023340fa17967c8093a26',
    messagingSenderId: '32021205715',
    projectId: 'olivosverdes-34cf7',
    authDomain: 'olivosverdes-34cf7.firebaseapp.com',
    storageBucket: 'olivosverdes-34cf7.firebasestorage.app',
  );

}